apiVersion: v1
kind: Service
metadata:
  name: benthos-service
  namespace: iot-gw-stack
spec:
  selector:
    app: benthos
  ports:
    - protocol: TCP
      port: 4195
      targetPort: 4195
  type: NodePort  # or LoadBalancer if you are in a cloud environment
