input:
  label: ""
  http_server:
    address: ""
    path: /post
    ws_path: /post/ws
    allowed_verbs:
      - POST
    timeout: 5s
    rate_limit: ""
pipeline:
  processors:
    - bloblang: |
        root.timestamp = now().format_timestamp("2006-01-02T15:04:05Z07:00")
        root.message = this
output:
  stdout: {}