apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/benthos

# Generate a ConfigMap from a file
configMapGenerator:
  - name: benthos-config
    behavior: create
    files:
      - common/benthos.yaml
  # - name: app2-config
    # literals:
    #   - ENV_SPECIFIC_VARIABLE=value-specific-to-machine-1

patches:
  - path: specific/benthos-patch.yaml
    target:
      kind: Deployment
      name: benthos